### PR TITLE
Add exceptions handling talk & article by Nikola Poša

### PR DESCRIPTION
**Pull request by OndraM**
Great talk & article by Nikola Poša about exceptions handling in PHP by @nikolaposa.
Talk from phpCE 2017: https://www.youtube.com/watch?v=1YAGxJVuuws
Article: https://blog.nikolaposa.in.rs/2016/08/17/exceptional-behavior-best-practices/

### CODE REVIEW

**Comment by ghost** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">When adding, please keep it to one new resource per one pull request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nikolaposa** [comment]
@OndraM Thanks for sharing! :+1:

**Review by legendik — APPROVED** [review]
👍

**Review by MortalFlesh — COMMENTED** [review]
Well I personally don't like this aproach I would much more prefer this https://vimeo.com/113707214 by @swlaschin even though we are mostly in OOP world...
Here is a simple example of RoP in PHP [example](https://github.com/MortalFlesh/examples/blob/master/RailwayOrientedProgramming/railway.php).

All work with Exceptions is IMHO quite hard and it can be simplified a lot by a simple `null` (_option type like_).
And with PHPStan I guess `null` is much better solution since you explicitelly tell `this might OR might NOT return something`

_Even *Yoda*_ sais...


IMHO you can prevent most exceptions by simply checking the behaviour before and then just do it .. or not.
OFC some exceptions could always be thrown (db, ...) but I guess these kind of exceptions should be catched only by top level listener just to prevent it from being shown to the user - not for tell the program what to do next. Otherwise Exceptions are just a pretty `goto`...

In the end - I dont say not to merge it or that this aproach is bad, I'm just trying to say that there are other solutions which might be better these days...

**Review by jirinovak — APPROVED** [review]

**Comment by OndraM** [comment]
@MortalFlesh Thanks for mentioning this and nice example :). 

Well, nobody says this is the only way. But from my experience in current PHP world these practices mentioned in the talk and article by Nikola ale quite good, address common mistakes, and if applied, they would improve even *most* of PHP codebase we have in LMC. And it is also greately actionable: you can easily start applying them.

What you are talking about is an interesting approach, but with a different paradigm, maybe even not suitable for today-PHP, and with concepts far away from problems PHP developers now actually face, IMO. So its good to know this approach if you are experienced and interested in some overlaping topics, but I'd say its not something widely applicable...

**Pull request merged**
